<?php

/**
 * ContentCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentComment');
    }
}